%% BrundageSoOp.m — main entry SCRIPT for Brundage SoOp post-processing.
% Detects Borah/local and batch/GUI modes; reruns append only new files.
% Configuration details: docs/config-reference.md.
% Author: Thomas Van Der Weide

%% Path setup (must be first — puts stages/rfi/lib/viewer/tools on the path)
soop_setup_paths;

%% Platform detection
on_hpc   = isunix;                  % Borah (Linux) vs local Windows
is_batch = batchStartupOptionUsed;  % true for matlab -batch; disables figures

%% Site configuration (per-site / per-machine values — edit site_config.json, NOT here)
% Edit site_config.json for paths, geometry, time zones, weather data, and satellite.
% Science parameters are configured below.
site = jsondecode(fileread(fullfile(fileparts(which('soop_setup_paths')), ...
                                    'site_config.json')));

%% Configuration (processing params identical on both systems)
% input_dir holds shared season inputs; out_dir is the dated run root.
% Products are written to Figures and L1 or a method-specific sibling directory.
if on_hpc
    % Supports the 2026 base and updated data-acquisition directory structures.
    paths = site.paths.hpc;
else
    % --- Local cryosoop B210 data --------------------------------------------
    % Set data_dir to the root above the <YYYYMMDD>/<HHMMSS> capture folders.
    % Refresh overflow_timestamps.txt with find_overflows after adding captures.
    % -------------------------------------------------------------------------
    paths = site.paths.local;
end
cfg.data_dir  = paths.data_dir;
cfg.input_dir = paths.input_dir;
cfg.out_dir   = paths.out_dir;
cfg.fig_dir = fullfile(cfg.out_dir, 'Figures');
cfg.out_dir = fullfile(cfg.out_dir, 'L1');
% SDR settings are defined in site_config.json; see docs/config-reference.md.
cfg.fs           = site.sdr.fs;            % sample rate (Hz)
cfg.Ti           = site.sdr.Ti;            % coherent integration time per segment (s)
cfg.num_segs     = site.sdr.num_segs;      % segments coherently averaged per file
cfg.peak_lag     = site.sdr.peak_lag;      % target lag (samples)
cfg.lag_half_win = site.sdr.lag_half_win;  % analysis window half-width (samples)
cfg.freq_hz      = site.sdr.freq_hz;       % center frequency (Hz)
cfg.tower_h_m    = site.site.tower_h_m;    % tower height (m)
cfg.T_load_K     = site.sdr.T_load_K;      % calibration load temperature (K)

% --- L2 geometric correction (site geometry from site_config.json) ---
% capture_tz is the time zone used in capture filename timestamps.
% Site geometry and time-zone details: docs/config-reference.md.
cfg.site_lat   = site.site.lat;      % deg N
cfg.site_lon   = site.site.lon;      % deg E
cfg.site_alt_m = site.site.alt_m;    % m, WGS84 ellipsoidal (antenna phase center)
cfg.capture_tz = site.site.capture_tz;
% Chain-phase cal reference (compute_L2): 0 = FULL per-session subtraction
% (decision 2026-07-17) — each capture is corrected by its own UHD session's
% measured inter-channel chain phase, no season-derived constant. The retired
% 2025-26 season-mean anchor (-81.4) and its history:
% docs/config-reference.md#chain-cal-knobs.
cfg.chain_phase_ref_deg = 0;
cfg.snr_threshold  = 10;        % dB; used by compare_sat_candidates scoring
% Overflow capture list generated by find_overflows.m.
cfg.overflow_file  = fullfile(cfg.input_dir, 'overflow_timestamps.txt');
% Weather data are used only for viewer overlays.
% wx_temp_cols maps to airtc_c, then temp_c.
cfg.wx_dat       = site.weather.wx_dat;
cfg.wx_temp_cols = reshape(site.weather.wx_temp_cols, 1, []);  % weather temperature column names
% Set wx_tz when logger timestamps need conversion to cfg.capture_tz.
% Leave unset to use weather timestamps as recorded.
if isfield(site.weather, 'wx_tz') && ~isempty(site.weather.wx_tz)
    cfg.wx_tz = site.weather.wx_tz;
end
% Elevation CSVs come from make_muos_elevation.py.
% cfg.elev_table selects site.season.norad for L2 processing.
cfg.elev_dir   = cfg.input_dir;
cfg.elev_table = fullfile(cfg.elev_dir, sprintf('muos_elevation_%d.csv', site.season.norad));
% Parallel-pool job storage on the HPC.
cfg.matlab_jobs_dir = site.paths.hpc.matlab_jobs;

% Minimum bytes per interleaved I/Q int16 channel file.
cfg.min_bytes    = cfg.fs * cfg.Ti * cfg.num_segs * 2 * 2;

% Number of pairs processed before each CSV append.
cfg.batch_size   = 200;
cfg.use_gpu      = false;       % use CPU parfor

% --- RFI excision (off by default; bands from compute_rfi_spectrum) ---
% Each method writes a separate product set; downstream stages process each set.
cfg.rfi_methods = {'notch_interp'};
% Set false to leave the base ('none') product set unchanged.
update_base = true;
if update_base, cfg.rfi_methods = [{'none'}, cfg.rfi_methods]; end
% Load signal RFI bands exported from the viewer; edit the CSV, not this script.
cfg.rfi_bands_file = fullfile(cfg.input_dir, 'rfi_bands.csv');
if isfile(cfg.rfi_bands_file)
    B = readtable(cfg.rfi_bands_file);
    cfg.rfi_bands = [B.f_lo_hz, B.f_hi_hz];   % N x 2 [f_lo_hz f_hi_hz], RF Hz
    fprintf('[BrundageSoOp] Loaded %d RFI band(s) from %s\n', ...
            size(cfg.rfi_bands, 1), cfg.rfi_bands_file);
else
    warning('BrundageSoOp:noRfiBands', ['rfi_bands_file not found (%s) — ' ...
            'notch will be a no-op (behaves like ''none'').'], cfg.rfi_bands_file);
    cfg.rfi_bands = [];
end
% Load separate NL and L calibration bands.
% Missing files leave that calibration state unexcised; signal bands are not reused.
for cal = ["NL" "L"]
    calfile = fullfile(cfg.input_dir, "rfi_bands_" + cal + ".csv");
    calfld  = "rfi_bands_" + lower(cal);
    if isfile(calfile)
        Bc = readtable(calfile);
        cfg.(calfld) = [Bc.f_lo_hz, Bc.f_hi_hz];   % N x 2 [f_lo_hz f_hi_hz], RF Hz
        fprintf('[BrundageSoOp] Loaded %d %s RFI band(s) from %s.\n', size(cfg.(calfld),1), cal, calfile);
    else
        cfg.(calfld) = zeros(0,2);                  % missing file leaves this state unexcised
        fprintf('[BrundageSoOp] No %s (rfi_bands_%s.csv) — %s calibration runs UNEXCISED.\n', calfile, cal, cal);
    end
end
% --- MUOS sub-channel bands (freq_muos frequency-domain comparison) ---
% RF bands used to calculate peak_phase_deg_fd_muos.
% Rows are [f_lo_hz f_hi_hz] for channels centered at 362.5–377.5 MHz.
cfg.muos_bands = 1e6 * [ ...
    360.20, 364.80;   % MUOS ch1 (center 362.5)
    365.20, 369.80;   % MUOS ch2 (center 367.5)
    370.20, 374.80;   % MUOS ch3 (center 372.5)
    375.20, 379.80];  % MUOS ch4 (center 377.5)
cfg.rfi_apply_calib  = true;       % apply excision to calibration captures
% Seed values for the viewer RFI explorer; tune there and export to rfi_bands.csv.
cfg.rfi_excess_db    = 3;          % flag bins this many dB above the smoothed PSD envelope
cfg.rfi_sk_threshold = 50;        % also flag bins with spectral kurtosis >= this (bursty RFI)
cfg.rfi_use_sk       = true;       % include the SK gate in the proposed bands
cfg.rfi_env_khz      = 500;       % PSD-envelope movmedian width
cfg.rfi_merge_khz    = 15;         % merge flagged runs closer than this into one band
cfg.rfi_edge_guard_khz = 0;        % drop the outer band edges (FFT-edge artifacts)
cfg.rfi_band_pad_khz = 1;          % widen each proposed band for the L1 notch
cfg.rfi_min_width_khz = 0.1;       % drop runs narrower than this

% --- Radar-equation calibration (compute_sigma0: apparent sigma0 + coherent reflectivity) ---
% Set antenna gains and polarizations in site_config.json.
% Measured values and limitations: docs/config-reference.md.
cfg.ant_gain_direct_dbi    = site.site.ant_gain_direct_dbi;     % dBic toward the satellite
cfg.ant_gain_reflected_dbi = site.site.ant_gain_reflected_dbi;  % dBic toward the specular point
cfg.ant_pol_direct         = site.site.ant_pol_direct;
cfg.ant_pol_reflected      = site.site.ant_pol_reflected;
cfg.sigma0_win_hours      = 24;        % sliding-window width (h)
cfg.sigma0_min_count      = 5;         % minimum valid captures per window
cfg.sigma0_min_elev_deg   = 5;         % minimum elevation (deg); lower captures excluded
cfg.sigma0_min_dsnr_db    = 10;        % minimum direct-channel SNR (dB)
cfg.sigma0_cal_max_age_hr = 1;         % maximum calibration age (h)
cfg.sigma0_corr_family    = 'fd_muos'; % correlation family for L1 amplitude and L2 phase

%% Processing toggles
% Process on the HPC by default; set toggles manually for local runs.
run_L1    = on_hpc;
run_calib = on_hpc;
run_snr   = false;   % needs the L1 CSV; run after the first full L1 pass
run_satid = false;    % compare_sat_candidates: produces sat_candidates_corrected.csv
run_L2    = false;    % needs cfg.elev_table for the CONFIRMED satellite
run_rfi   = false;   % compute_rfi_spectrum: season RFI diagnostic + proposed bands
run_sigma0 = false;  % compute_sigma0: needs L1 channel-power columns + L2 + calib in each method dir

%% Run pipeline (parpool sizing + stage dispatch + per-method downstream loop)
toggles.run_L1    = run_L1;
toggles.run_calib = run_calib;
toggles.run_snr   = run_snr;
toggles.run_satid = run_satid;
toggles.run_L2    = run_L2;
toggles.run_rfi   = run_rfi;
toggles.run_sigma0 = run_sigma0;
soop_run_pipeline(cfg, toggles);

%% Interactive viewer (skipped under matlab -batch: no display)
% To inspect excised products, set cfg.out_dir to the method directory and rerun.
if ~is_batch
    BrundageSoOp_viewer(cfg);
end
