function compute_snr(cfg)
% SNR distribution analysis for choosing an overflow-detection threshold.
%
% Run after the first full L1 pass on Borah. Loads BrundageSoOp_L1_sig.csv
% and optionally overflow_timestamps.txt (capture base names, one per line,
% generated by find_overflows.m from the Pi's sdr_capture.log).
% Plots overlapping SNR histograms:
%   1. All valid (non-rejected) files
%   2. Files flagged as overflowed in the capture log
% and prints a candidate low-SNR threshold.
%
% Output: cfg.out_dir/SNR_distribution.png (saved figure)
%         Candidate threshold printed to console
%
% Overflow list: prefers cfg.overflow_file (the stable season list, matching
% compute_L1/compute_calib and the viewer), falling back to the legacy
% cfg.out_dir/overflow_timestamps.txt when that field or file is absent.
%

    sig_csv    = fullfile(cfg.out_dir, 'BrundageSoOp_L1_sig.csv');
    if isfield(cfg, 'overflow_file') && isfile(cfg.overflow_file)
        ovfl_file = cfg.overflow_file;                                 % preferred
    else
        ovfl_file = fullfile(cfg.out_dir, 'overflow_timestamps.txt');  % legacy fallback (optional)
    end
    fig_out    = fullfile(cfg.out_dir, 'SNR_distribution.png');

    if ~isfile(sig_csv)
        fprintf('[SNR] %s not found — run compute_L1 first.\n', sig_csv);
        return;
    end

    T = readtable(sig_csv, 'TextType', 'string');
    if ~ismember('snr_db', T.Properties.VariableNames)
        fprintf('[SNR] snr_db column not found in %s\n', sig_csv);
        return;
    end

    % Drop non-finite SNR rows (noise_floor == 0 edge case writes Inf).
    n_dropped = sum(~isfinite(T.snr_db));
    if n_dropped > 0
        fprintf('[SNR] Dropping %d rows with non-finite SNR.\n', n_dropped);
        T = T(isfinite(T.snr_db), :);
    end

    snr_all = T.snr_db;
    fprintf('[SNR] Loaded %d rows from %s\n', height(T), sig_csv);
    fprintf('[SNR] SNR range: %.1f to %.1f dB\n', min(snr_all), max(snr_all));

    % Load overflow capture list (optional — base names, one per line,
    % from find_overflows.m). Exact base_name match: the log attributes
    % each overflow to the specific capture that was streaming.
    ovfl_mask = false(height(T), 1);
    if isfile(ovfl_file)
        ovfl_bases = strtrim(readlines(ovfl_file));
        ovfl_bases = ovfl_bases(strlength(ovfl_bases) > 0);
        ovfl_mask  = ismember(T.base_name, ovfl_bases);
        fprintf('[SNR] Flagged %d files listed as overflowed in the capture log.\n', ...
                sum(ovfl_mask));
    else
        fprintf('[SNR] No overflow file at %s — skipping overflow overlay.\n', ovfl_file);
    end

    % Candidate threshold: percentile below the main distribution.
    % (local_prctile avoids a Statistics Toolbox dependency)
    snr_p10 = local_prctile(snr_all, 10);
    snr_p25 = local_prctile(snr_all, 25);
    fprintf('[SNR] 10th percentile: %.1f dB  |  25th percentile: %.1f dB\n', snr_p10, snr_p25);
    fprintf('[SNR] Candidate threshold review: files with SNR < %.1f dB (10th pct)\n', snr_p10);

    % Plot.
    edges = min(snr_all)-1 : 0.5 : max(snr_all)+1;

    fig = figure('Visible', 'off', 'Position', [100 100 900 500]);
    hold on;

    histogram(snr_all, edges, 'FaceColor', [0.3 0.5 0.8], 'FaceAlpha', 0.6, ...
              'DisplayName', sprintf('All files (n=%d)', height(T)));

    if any(ovfl_mask)
        histogram(snr_all(ovfl_mask), edges, 'FaceColor', [0.9 0.3 0.2], 'FaceAlpha', 0.7, ...
                  'DisplayName', sprintf('Overflow-flagged (n=%d)', sum(ovfl_mask)));
    end

    xline(snr_p10, '--k', 'LineWidth', 1.5, 'DisplayName', ...
          sprintf('10th pct = %.1f dB', snr_p10));

    xlabel('SNR (dB)');
    ylabel('File count');
    title('Brundage SoOp — L1 SNR distribution');
    legend('Location', 'northwest');
    grid on;
    hold off;

    saveas(fig, fig_out);
    close(fig);
    fprintf('[SNR] Saved → %s\n', fig_out);
end


% =========================================================================
function p = local_prctile(x, pct)
% Percentile via linear interpolation (matches prctile's default method),
% without requiring the Statistics and Machine Learning Toolbox.
    x = sort(x(:));
    n = numel(x);
    if n == 1, p = x; return; end
    rank = pct/100 * n + 0.5;            % prctile convention
    rank = min(max(rank, 1), n);
    lo   = floor(rank);
    hi   = ceil(rank);
    p    = x(lo) + (rank - lo) * (x(hi) - x(lo));
end
